language: go

go:
  - 1.11.x
  - 1.12.x

install:
  - go get -v ./...

script:
  - go test -v -race -timeout=1m ./...
  - go test -v -timeout=1m -cover -coverprofile=coverage.out ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
